# Generated by Django 5.0.6 on 2024-06-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('premium', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('categoty', models.CharField(max_length=60)),
                ('elaboration_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('entry_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('food_state', models.IntegerField()),
                ('food_name', models.CharField(max_length=60)),
                ('food_price', models.IntegerField()),
                ('img_src', models.CharField(max_length=200)),
                ('food_amount', models.IntegerField()),
                ('consumed', models.IntegerField()),
                ('possible_expiration_date', models.DateField()),
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'food',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('inbox_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'inbox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NutritionalInfo',
            fields=[
                ('nutrit_info_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nutritional_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PossibleShop',
            fields=[
                ('poss_shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=60)),
                ('food_categoty', models.CharField(max_length=60)),
                ('details', models.CharField(max_length=100)),
                ('possbile_price', models.IntegerField()),
            ],
            options={
                'db_table': 'possible_shop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('publ_price', models.IntegerField()),
                ('publ_descp', models.CharField(max_length=800)),
                ('publ_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'publication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('intolerance_allergies', models.CharField(max_length=80)),
                ('home_size', models.IntegerField()),
                ('name_user', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
                ('month_budget', models.IntegerField()),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_count', models.IntegerField()),
            ],
            options={
                'db_table': 'user_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='media/')),
            ],
            options={
                'db_table': 'image',
                'managed': True,
            },
        ),
    ]
