# pull official base image
FROM python:3.11.4-slim-buster

# set work directory
RUN mkdir /app
WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt

# Expone el puerto en el que la aplicación correrá
EXPOSE 8000

# copy project
COPY . /app/


# Comando para correr la aplicación
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]