version: '3.8'

services:
  web:
    # containter_name: django-api
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - .:/app/
    ports:
      - 8000:8000
    # env_file:
    #   - ./.env.dev
    networks:
      - django_net
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - django_net
    ports:
      - 8001:5432

networks:
  django_net:

volumes:
  db-data: